spring:
    profiles:
        active:
        - dev
 

---- 
spring:
    profiles: dev
    application:
        name: client-config-dev



---- 
spring:
    profiles: test
    application:
        name: client-config-test